#!/usr/bin/env python3

import time
import sys
import os
import datetime



ip = "8.8.8.8" 
response = os.system("ping " + ip)

#and then check the response...
if response == 0:
  print (ip, 'success!')
else:
  print (ip, 'failure!')
  

#This is the forever loop
lastTime = datetime.datetime.now()
while True:
  period = datetime.datetime.now()
  
  if period.second % 2 == 0 and (period - lastTime).total_seconds() >= 1:
        print(period)
        lastTime = period
        
#End
