#!/usr/bin/env python3


import time
import sys
import os
import datetime
import smtplib, ssl
from time import gmtime, strftime 
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


ip = "8.8.8.8" 
response = os.system("ping " + ip)
sender_email = "email.com"
receiver_email = "email.com"
password = input("Type your password and press enter:")

message = MIMEMultipart("alternative")
message["Subject"] = "multipart test"
message["From"] = sender_email
message["To"] = receiver_email

while True:
  time.sleep (2)
  period = datetime.datetime.now()
  presentTime=strftime("%x %X", gmtime())
  if response ==0:
    print (ip, "is up! " + presentTime)
else:
  print (ip, 'is down! ' + presentTime)

       
if ping != server_status:
        if ping == 0:
            mail_contentup=(ip + " is now up " + current_time) #email "body"
            message.attach(MIMEText(mail_contentup, 'plain')) # attaching above variable to email
            session = smtplib.SMTP('smtp.gmail.com', 587) #use gmail with port
            session.starttls() #enable security
            session.login(sender_address, sender_pass) #login with mail_id and password
            text = message.as_string() # convert the message to string and assign to text variable
            session.sendmail(sender_address, receiver_address, text) # yeet that email out
            session.quit()
        else:
            mail_contentdown=(ip + " is now down " + current_time) #email "body"
            message.attach(MIMEText(mail_contentdown, 'plain')) # attaching above variable to email
            session = smtplib.SMTP('smtp.gmail.com', 587) #use gmail with port
            session.starttls() #enable security
            session.login(sender_address, sender_pass) #login with mail_id and password
            text = message.as_string() # convert the message to string and assign to text variable
            session.sendmail(sender_address, receiver_address, text) # yeet that email out
            session.quit()
            server_status=ping # change server_status variable to the new status given from ping



# End
